In [1]:
#importing libraries for one hot encoding
from tensorflow.keras.preprocessing.text import one_hot

C:\Users\PSingh\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\PSingh\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\PSingh\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\PSingh\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: P

In [2]:
txt=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
#size of vocabulary
vocab=10000

In [4]:
#representing the sentences as one hot encoding
onehot_rep=[one_hot(words,vocab) for words in txt]
onehot_rep

[[5077, 1025, 1445, 5808],
 [5077, 1025, 1445, 6718],
 [5077, 5585, 1445, 9535],
 [9757, 2114, 3479, 4237, 2635],
 [9757, 2114, 3479, 4237, 9674],
 [8290, 5077, 464, 1445, 7838],
 [7574, 3868, 9199, 4237]]

In [5]:
#importing libraries for embedding words
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
#padding the onehot rep for obtaining consistent dimensions in matrix while embedding
sent_length=8
padded_mat=pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(padded_mat)

[[   0    0    0    0 5077 1025 1445 5808]
 [   0    0    0    0 5077 1025 1445 6718]
 [   0    0    0    0 5077 5585 1445 9535]
 [   0    0    0 9757 2114 3479 4237 2635]
 [   0    0    0 9757 2114 3479 4237 9674]
 [   0    0    0 8290 5077  464 1445 7838]
 [   0    0    0    0 7574 3868 9199 4237]]


In [7]:
#preparing the model by applying embedding
dim=10   #dimension for embedding
model = Sequential()
model.add(Embedding(vocab,dim,input_length=sent_length))
model.compile('adam','mse')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.predict(padded_mat)

array([[[ 5.08903340e-03, -1.44235715e-02, -1.38436183e-02,
         -3.28990966e-02, -4.27976847e-02,  6.09221309e-03,
          1.29792728e-02, -2.99881455e-02, -6.31978363e-03,
          4.32964005e-02],
        [ 5.08903340e-03, -1.44235715e-02, -1.38436183e-02,
         -3.28990966e-02, -4.27976847e-02,  6.09221309e-03,
          1.29792728e-02, -2.99881455e-02, -6.31978363e-03,
          4.32964005e-02],
        [ 5.08903340e-03, -1.44235715e-02, -1.38436183e-02,
         -3.28990966e-02, -4.27976847e-02,  6.09221309e-03,
          1.29792728e-02, -2.99881455e-02, -6.31978363e-03,
          4.32964005e-02],
        [ 5.08903340e-03, -1.44235715e-02, -1.38436183e-02,
         -3.28990966e-02, -4.27976847e-02,  6.09221309e-03,
          1.29792728e-02, -2.99881455e-02, -6.31978363e-03,
          4.32964005e-02],
        [-2.80598756e-02, -6.85598701e-03, -2.20561158e-02,
         -1.24563202e-02, -2.21480615e-02,  4.63933386e-02,
         -3.85839343e-02, -3.75046730e-02,  2.114119

In [10]:
#resulted feature value prediction is a 3 dimensional matrix 8 x 10 x 7 
#padded sentence length x feature_dimensions x number of sentences